/* CAS2107-01 Programming Assignment #1 - example runner.
 *
 * You do NOT edit this file. It reads one input file and prints the result of
 * every step of a single quantized matrix multiplication, so that you can
 * compare your output with the expected output in the examples directory.
 *
 * Input format (whitespace separated):
 *
 *     M K N
 *     M*K floats   the activation matrix A
 *     K*N floats   the weight matrix B
 */

#include "quant.h"

#include <stdio.h>
#include <stdlib.h>

#define MAX_ELEMS 4096

static float a_f[MAX_ELEMS], b_f[MAX_ELEMS], c_f[MAX_ELEMS];
static int8_t a_q[MAX_ELEMS], b_q[MAX_ELEMS], out_q[MAX_ELEMS];
static int32_t acc[MAX_ELEMS];
static float out_f[MAX_ELEMS];

static void read_floats(FILE *f, float *dst, int n, const char *what)
{
    for (int i = 0; i < n; ++i) {
        if (fscanf(f, "%f", &dst[i]) != 1) {
            fprintf(stderr, "bad input: expected %d values for %s\n", n, what);
            exit(1);
        }
    }
}

static void minmax(const float *v, int n, float *lo, float *hi)
{
    float a = v[0], b = v[0];
    for (int i = 1; i < n; ++i) {
        if (v[i] < a) a = v[i];
        if (v[i] > b) b = v[i];
    }
    *lo = a; *hi = b;
}

static void minmax_i32(const int32_t *v, int n, int32_t *lo, int32_t *hi)
{
    int32_t a = v[0], b = v[0];
    for (int i = 1; i < n; ++i) {
        if (v[i] < a) a = v[i];
        if (v[i] > b) b = v[i];
    }
    *lo = a; *hi = b;
}

static void print_params(const char *label, float lo, float hi, QParams p)
{
    printf("%s(%.6f, %.6f) = {scale=%.8f, zero_point=%d}\n",
           label, lo, hi, p.scale, p.zero_point);
}

static void print_codes(const char *label, const int8_t *q, int n)
{
    printf("%s = [", label);
    for (int i = 0; i < n; ++i) printf("%s%d", i ? ", " : "", (int)q[i]);
    printf("]\n");
}

static void print_acc(const char *label, const int32_t *v, int n)
{
    printf("%s = [", label);
    for (int i = 0; i < n; ++i) printf("%s%d", i ? ", " : "", v[i]);
    printf("]\n");
}

static void print_floats(const char *label, const float *v, int n)
{
    printf("%s = [", label);
    for (int i = 0; i < n; ++i) printf("%s%.6f", i ? ", " : "", v[i]);
    printf("]\n");
}

int main(int argc, char **argv)
{
    FILE *f = stdin;
    if (argc > 1) {
        f = fopen(argv[1], "r");
        if (f == NULL) { fprintf(stderr, "cannot open %s\n", argv[1]); return 1; }
    }

    int M, K, N;
    if (fscanf(f, "%d %d %d", &M, &K, &N) != 3) {
        fprintf(stderr, "bad input: expected M K N\n");
        return 1;
    }
    if (M <= 0 || K <= 0 || N <= 0 ||
        M * K > MAX_ELEMS || K * N > MAX_ELEMS || M * N > MAX_ELEMS) {
        fprintf(stderr, "bad input: dimensions out of range\n");
        return 1;
    }
    read_floats(f, a_f, M * K, "A");
    read_floats(f, b_f, K * N, "B");
    if (f != stdin) fclose(f);

    printf("shapes: A is %dx%d, B is %dx%d, C is %dx%d\n", M, K, K, N, M, N);

    /* ---- step 1: choose parameters and quantize both matrices ---------- */
    float lo, hi;
    minmax(a_f, M * K, &lo, &hi);
    QParams pa = qp_from_minmax(lo, hi);
    print_params("qp_from_minmax/A", lo, hi, pa);
    quantize_tensor(a_f, a_q, (size_t)(M * K), pa);
    print_codes("quantize_tensor/A", a_q, M * K);

    minmax(b_f, K * N, &lo, &hi);
    QParams pb = qp_from_minmax(lo, hi);
    print_params("qp_from_minmax/B", lo, hi, pb);
    quantize_tensor(b_f, b_q, (size_t)(K * N), pb);
    print_codes("quantize_tensor/B", b_q, K * N);

    /* ---- step 2: the two matrix products ------------------------------- */
    gemm_i8(a_q, b_q, acc, M, K, N, pa.zero_point, pb.zero_point);
    print_acc("gemm_i8", acc, M * N);

    gemm_f32(a_f, b_f, c_f, M, K, N);
    print_floats("gemm_f32", c_f, M * N);

    /* ---- step 3: fold the accumulator back down to INT8 ---------------- */
    const float acc_scale = pa.scale * pb.scale;
    int32_t amin, amax;
    minmax_i32(acc, M * N, &amin, &amax);
    QParams pout = qp_from_minmax((float)amin * acc_scale, (float)amax * acc_scale);
    print_params("qp_from_minmax/acc", (float)amin * acc_scale,
                 (float)amax * acc_scale, pout);
    requantize_tensor(acc, out_q, (size_t)(M * N), pa.scale, pb.scale, pout);
    print_codes("requantize_tensor", out_q, M * N);

    dequantize_tensor(out_q, out_f, (size_t)(M * N), pout);
    print_floats("dequantize_tensor", out_f, M * N);

    /* ---- step 4: how far the integer path drifted ---------------------- */
    float worst = 0.0f;
    for (int i = 0; i < M * N; ++i) {
        float d = out_f[i] - c_f[i];
        if (d < 0.0f) d = -d;
        if (d > worst) worst = d;
    }
    printf("max abs error vs gemm_f32 = %.6f  (requantization step = %.6f)\n",
           worst, pout.scale);
    return 0;
}
