/* CAS2107-01 Programming Assignment #1 - MNIST multi-layer benchmark.
 *
 * You do NOT edit this file. It reads three matrices sampled from MNIST data
 * and runs a two-layer Float32 and INT8 path:
 *
 *     hidden = ReLU(A * W1)
 *     output = hidden * W2
 *
 * The INT8 path requantizes the first layer accumulator before the second
 * GEMM. The program reports numerical error and average end-to-end latency.
 *
 * Binary input format (little-endian):
 *
 *     int32_t M, K, H, N
 *     M*K Float32 values for A
 *     K*H Float32 values for W1
 *     H*N Float32 values for W2
 */

#define _POSIX_C_SOURCE 200809L

#include "quant.h"

#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

typedef struct {
    int m, k, h, n;
    float *a, *w1, *w2;
} Input;

typedef struct {
    int8_t *aq, *w1q, *w2q, *hq;
    int32_t *acc1, *acc2;
    float *hidden_deq;
    QParams pa, pw1, pw2, ph;
} IntWorkspace;

static uint64_t monotonic_ns(void)
{
    struct timespec t;
    if (clock_gettime(CLOCK_MONOTONIC, &t) != 0) return 0;
    return (uint64_t)t.tv_sec * UINT64_C(1000000000) + (uint64_t)t.tv_nsec;
}

static void *xmalloc(size_t bytes)
{
    void *p = malloc(bytes);
    if (p == NULL) {
        fprintf(stderr, "out of memory\n");
        exit(1);
    }
    return p;
}

static void die_input(const char *path)
{
    fprintf(stderr, "cannot read MNIST matrix data from %s\n", path);
    exit(1);
}

static void minmax_f32(const float *v, size_t n, float *lo, float *hi)
{
    float a = v[0], b = v[0];
    for (size_t i = 1; i < n; ++i) {
        if (v[i] < a) a = v[i];
        if (v[i] > b) b = v[i];
    }
    *lo = a;
    *hi = b;
}

static void minmax_i32(const int32_t *v, size_t n, int32_t *lo, int32_t *hi)
{
    int32_t a = v[0], b = v[0];
    for (size_t i = 1; i < n; ++i) {
        if (v[i] < a) a = v[i];
        if (v[i] > b) b = v[i];
    }
    *lo = a;
    *hi = b;
}

static void load_input(const char *path, Input *in)
{
    FILE *f = fopen(path, "rb");
    if (f == NULL) die_input(path);

    int32_t shape[4];
    if (fread(shape, sizeof shape, 1, f) != 1 ||
        shape[0] <= 0 || shape[1] <= 0 ||
        shape[2] <= 0 || shape[3] <= 0) {
        fclose(f);
        die_input(path);
    }

    in->m = shape[0];
    in->k = shape[1];
    in->h = shape[2];
    in->n = shape[3];
    const size_t na = (size_t)in->m * in->k;
    const size_t nw1 = (size_t)in->k * in->h;
    const size_t nw2 = (size_t)in->h * in->n;

    in->a = xmalloc(na * sizeof(float));
    in->w1 = xmalloc(nw1 * sizeof(float));
    in->w2 = xmalloc(nw2 * sizeof(float));
    if (fread(in->a, sizeof(float), na, f) != na ||
        fread(in->w1, sizeof(float), nw1, f) != nw1 ||
        fread(in->w2, sizeof(float), nw2, f) != nw2) {
        fclose(f);
        die_input(path);
    }
    fclose(f);
}

static QParams quantize_one(const float *src, int8_t *dst, size_t count)
{
    float lo, hi;
    minmax_f32(src, count, &lo, &hi);
    QParams p = qp_from_minmax(lo, hi);
    quantize_tensor(src, dst, count, p);
    return p;
}

static void forward_f32(const Input *in, float *hidden, float *output)
{
    gemm_f32(in->a, in->w1, hidden, in->m, in->k, in->h);
    const size_t count = (size_t)in->m * in->h;
    for (size_t i = 0; i < count; ++i)
        if (hidden[i] < 0.0f) hidden[i] = 0.0f;
    gemm_f32(hidden, in->w2, output, in->m, in->h, in->n);
}

static void first_i8_layer(const Input *in, IntWorkspace *w)
{
    gemm_i8(w->aq, w->w1q, w->acc1, in->m, in->k, in->h,
            w->pa.zero_point, w->pw1.zero_point);
    const size_t count = (size_t)in->m * in->h;
    for (size_t i = 0; i < count; ++i)
        if (w->acc1[i] < 0) w->acc1[i] = 0;
}

static void forward_i8(const Input *in, IntWorkspace *w)
{
    const size_t hidden_count = (size_t)in->m * in->h;
    first_i8_layer(in, w);
    requantize_tensor(w->acc1, w->hq, hidden_count,
                      w->pa.scale, w->pw1.scale, w->ph);
    gemm_i8(w->hq, w->w2q, w->acc2, in->m, in->h, in->n,
            w->ph.zero_point, w->pw2.zero_point);
}

static double relative_l2(const float *expected, const float *actual,
                          size_t count, double *max_error)
{
    double error2 = 0.0, expected2 = 0.0, worst = 0.0;
    for (size_t i = 0; i < count; ++i) {
        const double error = (double)actual[i] - expected[i];
        const double absolute = fabs(error);
        error2 += error * error;
        expected2 += (double)expected[i] * expected[i];
        if (absolute > worst) worst = absolute;
    }
    *max_error = worst;
    return expected2 > 0.0 ? sqrt(error2 / expected2) * 100.0 : 0.0;
}

int main(int argc, char **argv)
{
    const char *path = "data/mnist_gemm.bin";
    int repetitions = argc > 1 ? atoi(argv[1]) : 200;
    if (argc > 2 || repetitions < 1) {
        fprintf(stderr, "Usage: %s [repetitions]\n", argv[0]);
        return 1;
    }

    Input in;
    load_input(path, &in);
    const size_t na = (size_t)in.m * in.k;
    const size_t nw1 = (size_t)in.k * in.h;
    const size_t nw2 = (size_t)in.h * in.n;
    const size_t nh = (size_t)in.m * in.h;
    const size_t no = (size_t)in.m * in.n;

    float *hidden = xmalloc(nh * sizeof(float));
    float *output = xmalloc(no * sizeof(float));
    float *output_i8 = xmalloc(no * sizeof(float));
    IntWorkspace w;
    w.aq = xmalloc(na);
    w.w1q = xmalloc(nw1);
    w.w2q = xmalloc(nw2);
    w.hq = xmalloc(nh);
    w.acc1 = xmalloc(nh * sizeof(int32_t));
    w.acc2 = xmalloc(no * sizeof(int32_t));
    w.hidden_deq = xmalloc(nh * sizeof(float));

    w.pa = quantize_one(in.a, w.aq, na);
    w.pw1 = quantize_one(in.w1, w.w1q, nw1);
    w.pw2 = quantize_one(in.w2, w.w2q, nw2);

    forward_f32(&in, hidden, output);
    first_i8_layer(&in, &w);
    int32_t amin, amax;
    minmax_i32(w.acc1, nh, &amin, &amax);
    const float first_scale = w.pa.scale * w.pw1.scale;
    w.ph = qp_from_minmax((float)amin * first_scale,
                          (float)amax * first_scale);
    forward_i8(&in, &w);

    uint64_t start = monotonic_ns();
    for (int r = 0; r < repetitions; ++r)
        forward_f32(&in, hidden, output);
    const uint64_t f32_ns = monotonic_ns() - start;

    start = monotonic_ns();
    for (int r = 0; r < repetitions; ++r)
        forward_i8(&in, &w);
    const uint64_t i8_ns = monotonic_ns() - start;

    dequantize_tensor(w.hq, w.hidden_deq, nh, w.ph);
    const float output_scale = w.ph.scale * w.pw2.scale;
    for (size_t i = 0; i < no; ++i)
        output_i8[i] = (float)w.acc2[i] * output_scale;

    double hidden_max, output_max;
    const double hidden_error = relative_l2(hidden, w.hidden_deq, nh, &hidden_max);
    const double output_error = relative_l2(output, output_i8, no, &output_max);
    const double f32_us = (double)f32_ns / 1e3 / repetitions;
    const double i8_us = (double)i8_ns / 1e3 / repetitions;

    printf("layers:   %d x %d -> %d -> %d\n", in.m, in.k, in.h, in.n);
    printf("accuracy: hidden L2 = %.4f%%, output L2 = %.4f%%, max error = %.6f\n",
           hidden_error, output_error, output_max);
    printf("latency:  float32 = %.2f us, int8 = %.2f us, float/int8 = %.2fx\n",
           f32_us, i8_us, i8_us > 0.0 ? f32_us / i8_us : 0.0);

    free(in.a);
    free(in.w1);
    free(in.w2);
    free(hidden);
    free(output);
    free(output_i8);
    free(w.aq);
    free(w.w1q);
    free(w.w2q);
    free(w.hq);
    free(w.acc1);
    free(w.acc2);
    free(w.hidden_deq);
    return 0;
}
